version: '3.8'
services:
  neo4j:
    image: neo4j:5.18-community
    container_name: rpg-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test1234
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
  redis:
    image: redis:7-alpine
    container_name: rpg-redis
    ports:
      - "6380:6379"
volumes:
  neo4j_data:
  neo4j_logs:
