name: CI

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    env:
      CODACY_ORG_PROVIDER: gh
      CODACY_ORG_NAME: ceponatia
      CODACY_REPO_NAME: llm-rpg
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm (corepack)
        run: |
          corepack enable
          corepack prepare pnpm@9.0.0 --activate
          pnpm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint (ESLint)
        run: pnpm lint

      - name: Markdown Lint
        run: pnpm lint:md || true

      - name: Format check (Prettier)
        run: pnpm format:check || true

      - name: Run tests with coverage
        run: pnpm coverage:all

      - name: Verify combined lcov not empty
        run: |
          COUNT=$(grep -c '^SF:' coverage/combined.lcov || true)
          echo "File entries: $COUNT"
          if [ "$COUNT" -eq 0 ]; then
            echo 'ERROR: combined.lcov contains zero source files.'
            exit 1
          fi

      - name: Upload coverage to Codacy
        if: ${{ env.CODACY_PROJECT_TOKEN != '' && (github.event_name == 'pull_request' || github.ref == 'refs/heads/main') }}
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699
        with:
          project-token: ${{ env.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/combined.lcov

      - name: Summary
        if: always()
        run: |
          echo 'CI pipeline completed.'
          echo 'Lint / format steps are currently non-blocking if they used || true.'
