name: Coverage & Codacy Upload

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CODACY_ORG_PROVIDER: gh
      CODACY_ORG_NAME: ceponatia
      CODACY_REPO_NAME: llm-rpg
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
    steps:
      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Run coverage (all packages)
        run: pnpm coverage:all

      - name: Aggregate debug (list found lcov.info files)
        run: |
          echo 'Searching for lcov.info files:'
          find packages -type f -path '*/coverage/lcov.info' -print || true
          if [ ! -f coverage/combined.lcov ]; then
            echo 'combined.lcov missing AFTER coverage run.'
            ls -R . | head -n 200 || true
          fi

      - name: Verify Codacy token present
        run: |
          if [ -z "${{ env.CODACY_PROJECT_TOKEN }}" ]; then
            echo 'ERROR: CODACY_PROJECT_TOKEN not set (add it in Settings > Secrets and variables > Actions)';
            exit 1;
          fi
          echo "Codacy project token detected (length=${#CODACY_PROJECT_TOKEN})."

      - name: Verify lcov not empty
        run: |
          if [ ! -f coverage/combined.lcov ]; then
            echo 'ERROR: coverage/combined.lcov not found.'
            exit 1
          fi
          COUNT=$(grep -c '^SF:' coverage/combined.lcov || true)
          echo "Source file count: $COUNT"
            # Show path samples
          grep '^SF:' coverage/combined.lcov | head -n 20 || true
          if [ "$COUNT" -eq 0 ]; then
            echo 'ERROR: combined.lcov contains zero source files.'
            exit 1
          fi

      - name: Upload coverage to Codacy (official action)
        if: ${{ env.CODACY_PROJECT_TOKEN != '' && (github.event_name == 'pull_request' || github.ref == 'refs/heads/main') }}
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699
        with:
          project-token: ${{ env.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/combined.lcov

      - name: Upload coverage artifact (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-combined
          path: |
            coverage/combined.lcov
            packages/**/coverage/lcov.info
          if-no-files-found: warn

      - name: Failure summary
        if: failure()
        run: |
          echo 'Coverage job failed. See collected artifacts for investigation.'
