name: Coverage & Codacy Upload

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CODACY_ORG_PROVIDER: gh
      CODACY_ORG_NAME: ceponatia
      CODACY_REPO_NAME: llm-rpg
  # Static Codacy project token injected from repository secrets (add in GitHub Settings > Secrets > Actions)
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (enable Corepack for pnpm)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Enable Corepack
        run: corepack enable

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run coverage (all packages)
        run: pnpm coverage:all

      - name: Verify lcov not empty
        run: |
          COUNT=$(grep -c '^SF:' coverage/combined.lcov || true)
          echo "Source file count: $COUNT"
            if [ "$COUNT" -eq 0 ]; then
              echo 'ERROR: combined.lcov contains zero source files.'
              exit 1
            fi

      - name: Show combined lcov summary
        run: |
          echo 'File count:'
          grep -c '^SF:' coverage/combined.lcov || true
          echo 'First 5 lines:'
          head -n 5 coverage/combined.lcov || true

      - name: Upload coverage to Codacy
        if: ${{ env.CODACY_PROJECT_TOKEN != '' }}
        env:
          CODACY_PROJECT_TOKEN: ${{ env.CODACY_PROJECT_TOKEN }}
        run: |
          set -euo pipefail
          echo "Event: $GITHUB_EVENT_NAME Ref: $GITHUB_REF"
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ] || { [ "$GITHUB_EVENT_NAME" = "push" ] && [ "$GITHUB_REF" = "refs/heads/main" ]; }; then
            echo 'Uploading coverage to Codacy...'
            curl -Ls https://coverage.codacy.com/get.sh | bash -s report -r coverage/combined.lcov || { echo 'Codacy upload failed'; exit 1; }
          else
            echo 'Skipping Codacy upload (not main push or PR).'
          fi

      - name: Skip upload (no token available)
        run: |
          if [ -z "${{ env.CODACY_PROJECT_TOKEN }}" ]; then
            echo 'No Codacy token available; skipping coverage upload.'
          fi
