name: Coverage & Codacy Upload

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CODACY_ORG_PROVIDER: gh
      CODACY_ORG_NAME: ceponatia
      CODACY_REPO_NAME: llm-rpg
  # Static Codacy project token injected from repository secrets (add in GitHub Settings > Secrets > Actions)
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (enable Corepack for pnpm)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Enable Corepack
        run: corepack enable

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run coverage (all packages)
        run: pnpm coverage:all

      - name: Verify lcov not empty
        run: |
          COUNT=$(grep -c '^SF:' coverage/combined.lcov || true)
          echo "Source file count: $COUNT"
            if [ "$COUNT" -eq 0 ]; then
              echo 'ERROR: combined.lcov contains zero source files.'
              exit 1
            fi

      - name: Show combined lcov summary
        run: |
          echo 'File count:'
          grep -c '^SF:' coverage/combined.lcov || true
          echo 'First 5 lines:'
          head -n 5 coverage/combined.lcov || true

      - name: Upload coverage to Codacy (official action)
        if: ${{ env.CODACY_PROJECT_TOKEN != '' && (github.event_name == 'pull_request' || github.ref == 'refs/heads/main') }}
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ env.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/combined.lcov
          # Optionally specify commit if needed (defaults to current):
          # commit-uuid: ${{ github.sha }}

      - name: Skip upload (no token available)
        run: |
          if [ -z "${{ env.CODACY_PROJECT_TOKEN }}" ]; then
            echo 'No Codacy token available; skipping coverage upload.'
          fi
