name: Coverage & Codacy Upload

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CODACY_ORG_PROVIDER: gh
      CODACY_ORG_NAME: ceponatia
      CODACY_REPO_NAME: llm-rpg
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (enable Corepack for pnpm)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Enable Corepack
        run: corepack enable

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run coverage (all packages)
        run: pnpm coverage:all

      - name: Verify lcov not empty
        run: |
          COUNT=$(grep -c '^SF:' coverage/combined.lcov || true)
          echo "Source file count: $COUNT"
            if [ "$COUNT" -eq 0 ]; then
              echo 'ERROR: combined.lcov contains zero source files.'
              exit 1
            fi

      - name: Show combined lcov summary
        run: |
          echo 'File count:'
          grep -c '^SF:' coverage/combined.lcov || true
          echo 'First 5 lines:'
          head -n 5 coverage/combined.lcov || true

      - name: Obtain Codacy project token (dynamic)
        id: codacy_token
        env:
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN || '' }}
          CODACY_PROJECT_TOKEN_STATIC: ${{ secrets.CODACY_PROJECT_TOKEN || '' }}
        run: |
          if [ -n "$CODACY_PROJECT_TOKEN_STATIC" ]; then
            echo "codacy_project_token=$CODACY_PROJECT_TOKEN_STATIC" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          if [ -z "$CODACY_API_TOKEN" ]; then
            echo 'No static project token or API token; skipping token generation.'
            exit 0
          fi
          node scripts/codacy-get-or-create-project-token.mjs | tail -n 1 | sed 's/^TOKEN=//' > token.txt
          TOK=$(cat token.txt)
          echo "codacy_project_token=$TOK" >> "$GITHUB_OUTPUT"

      - name: Set Codacy project token env
        run: |
          TOKEN="${{ steps.codacy_token.outputs.codacy_project_token }}"
          if [ -n "$TOKEN" ]; then
            echo "CODACY_PROJECT_TOKEN=$TOKEN" >> $GITHUB_ENV
          fi

      - name: Upload coverage to Codacy
        if: ${{ env.CODACY_PROJECT_TOKEN }}
        env:
          CODACY_PROJECT_TOKEN: ${{ env.CODACY_PROJECT_TOKEN }}
        run: |
          set -euo pipefail
          echo "Event: $GITHUB_EVENT_NAME Ref: $GITHUB_REF"
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ] || { [ "$GITHUB_EVENT_NAME" = "push" ] && [ "$GITHUB_REF" = "refs/heads/main" ]; }; then
            echo 'Uploading coverage to Codacy...'
            curl -Ls https://coverage.codacy.com/get.sh | bash -s report -r coverage/combined.lcov || { echo 'Codacy upload failed'; exit 1; }
          else
            echo 'Skipping Codacy upload (not main push or PR).'
          fi

      - name: Skip upload (no token available)
        run: |
          if [ -z "${{ env.CODACY_PROJECT_TOKEN || '' }}" ]; then
            echo 'No Codacy token available; skipping coverage upload.'
          fi
