name: Format

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (enable Corepack for pnpm)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Enable Corepack
        run: corepack enable

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Prettier format check
        run: pnpm format:check

      - name: Summary
        if: always()
        run: |
          echo 'Prettier format check completed.'
          echo 'Failures above indicate files not formatted; run pnpm format locally to fix.'