name: Quality

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment (checkout + node + pnpm install)
        uses: ./.github/actions/setup-env

      - name: Restore ESLint cache
        uses: actions/cache@v4
        with:
          path: .eslintcache
          key: eslint-${{ runner.os }}-${{ hashFiles('eslint.config.mjs','packages/**/*.ts','packages/**/*.tsx') }}
          restore-keys: |
            eslint-${{ runner.os }}-

      - name: ESLint (check only)
        run: pnpm lint:check --cache --cache-location .eslintcache

      - name: Prettier (format check)
        run: pnpm format:check

      - name: Upload quality artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: quality-logs
          path: |
            .eslintcache
          if-no-files-found: ignore

      - name: Export summary
        if: always()
        run: |
          echo 'Quality checks completed.'
          echo 'Includes: ESLint (no --fix), Prettier check.'
