name: Security Scan (Weekly)

on:
  schedule:
    - cron: '0 3 * * 1' # Mondays 03:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trivy-fs:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Trivy filesystem scan (vulns, high+)
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # 0.32.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          format: 'table'
          exit-code: '0' # Do not fail the build yet; informational

      - name: Advisory
        run: |
          echo 'Review HIGH/CRITICAL findings above. Convert to required gate once noise is triaged.'